name       : perl-gtk3-simplelist
version    : '0.21'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/T/TV/TVIGNAUD/Gtk3-SimpleList-0.21.tar.gz : 1d4465100bf3bc0474a29469a406fd033562b6e3736188121000372ab2ada884
license    : |
    - GPL-2.0-or-later
    - Artistic-2.0
component  : programming.perl
summary    : This module provides a helper module for Gtk3.
description: |
    This module provides a helper module for Gtk3. It's based on Gtk2::SimpleList.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - perl-gtk3
rundeps    :
    - perl-gtk3
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
