name       : perl-gtk3-simplelist
version    : 0.17
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/T/TV/TVIGNAUD/Gtk3-SimpleList-0.17.tar.gz : ed201f74a9ff3542b7cc260159e87ca5894c24a5b182a39d6f86bb84669c9053
license    : |
    - GPL-2.0-or-later
    - Artistic-2.0
component  : programming.perl
summary    : This module provides a helper module for Gtk3.
description: |
    This module provides a helper module for Gtk3. It's based on Gtk2::SimpleList.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - perl-gtk3
rundeps    :
    - perl-gtk3
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
